# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  rime-flypy = {
    pname = "rime-flypy";
    version = "ea9455f25995a2878485c85b111c34a2a897adac";
    src = fetchFromGitHub {
      owner = "cubercsl";
      repo = "rime-flypy";
      rev = "ea9455f25995a2878485c85b111c34a2a897adac";
      fetchSubmodules = false;
      sha256 = "sha256-Lw54pNXUzsVv9OFp7c5Bf+pCCA0DWTslSTrN/raX9CM=";
    };
    date = "2025-12-27";
  };
  rime-prelude = {
    pname = "rime-prelude";
    version = "db691d2420b8e656a79692a94f9db0fb3e7aa12b";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-prelude";
      rev = "db691d2420b8e656a79692a94f9db0fb3e7aa12b";
      fetchSubmodules = false;
      sha256 = "sha256-sllcT3Kq572xJvlh+j4zN0AUblFzXlhZtL9RGT/GY7g=";
    };
    date = "2025-12-30";
  };
}
